; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = platformio-override.ini
default_envs = 
	esp32-s3-devkitc-1
	lolin_d32_pro_sdmmc_pe

[env]
board_build.flash_mode = qio
board_build.bootloader = dio
board_build.partitions = custom_4mb_noota.csv
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
framework = 
	arduino
	espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
extra_scripts = 
	pre:install_dependencies.py
	pre:gitVersion.py
	pre:platformInfo.py
	pre:updateSdkConfig.py
	pre:processHtml.py
lib_deps = 
	https://github.com/Joe91/ESP32-audioI2S.git#3c2a6b804afcb796fdefc755570ac28f6198d5e5
	https://github.com/madhephaestus/ESP32Encoder.git#7501cb47ec702c43de3c64df56d0b10930b9bc70
	https://github.com/Joe91/ESP-FTP-Server-Lib.git#517a2c90876659bfd6692d1f464784a05296e8d8
	https://github.com/FastLED/FastLED.git#20667c3a6413ed46a828f78ec95fb57e58d753f8
	https://github.com/ESP32Async/ESPAsyncWebServer.git#d6aa7daf0823a41966b1841826cff015237d6e42
	https://github.com/bblanchon/ArduinoJson.git#77771d3c07668e01d8f52acb03910c1110bb373f
	https://github.com/pschatzmann/arduino-audio-tools.git#b4b32dc849233e1c51424221951c9f5c576671e5
	https://github.com/pschatzmann/ESP32-A2DP.git#b6da4744286ca15b6f1dee607c077a4747294dd4
	https://github.com/Arduino-IRremote/Arduino-IRremote.git#498dc591b255d8ba2e239c875804bdab2ab0fe91
	https://github.com/Joe91/MFRC522_I2C.git#3cabf223fb6b2950474ff41f70c28922f8551341
	https://github.com/tueddy/rfid.git#caa3e6d4f9cc592e800b4467d61d64f765c3156f
	https://github.com/tuniii/LogRingBuffer.git#89d7d3e5b74e773cae38345e23ddaf2c4fd3e367
	https://github.com/biologist79/PN5180-Library.git#2479510696c81860938453a7e754da0d7cd1e20b
	https://github.com/tueddy/natsort.git#ebbf6604c573c5315daa8fa77da8f047f202bd63
board_build.embed_txtfiles = 
	managed_components/espressif__esp_insights/server_certs/https_server.crt
	managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
	managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
	managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt
build_flags = 
	-DCONFIG_ASYNC_TCP_RUNNING_CORE=0
	-DCONFIG_ASYNC_TCP_USE_WDT=1
	-DCORE_DEBUG_LEVEL=0
	-DCONFIG_FATFS_USE_LABEL=1
	-DENABLE_FTP_SANITIZATION
	-std=c++17
	-std=gnu++17
	-Wall
	-Wextra
	-Wunreachable-code
build_unflags = 
	-std=gnu++11
	-Werror=all

[env:lolin_d32_pro]
board = lolin_d32_pro
board_build.partitions = custom_16mb_ota.csv
build_flags = 
	${env.build_flags}
	-DHAL=4
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DLOG_BUFFER_SIZE=10240
	-DBOARD_HAS_16MB_FLASH_AND_OTA_SUPPORT
board_upload.maximum_size = 16777216
board_upload.flash_size = 16MB

[env:lolin_d32_pro_sdmmc_pe]
board = lolin_d32_pro
board_build.partitions = custom_16mb_ota.csv
build_flags = 
	${env.build_flags}
	-DHAL=7
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DLOG_BUFFER_SIZE=10240
	-DBOARD_HAS_16MB_FLASH_AND_OTA_SUPPORT
board_upload.maximum_size = 16777216
board_upload.flash_size = 16MB

[env:ttgo_t8]
board = esp-wrover-kit
build_flags = 
	${env.build_flags}
	-DHAL=5
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DLOG_BUFFER_SIZE=10240

[env:complete]
board = esp-wrover-kit
board_build.partitions = custom_16mb_ota.csv
build_flags = 
	${env.build_flags}
	-DHAL=6
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DLOG_BUFFER_SIZE=10240
	-DBOARD_HAS_16MB_FLASH_AND_OTA_SUPPORT
board_upload.maximum_size = 16777216
board_upload.flash_size = 16MB

[env:esp32-wrover-devkitc-v4-8mb]
board = esp-wrover-kit
board_build.partitions = custom_8mb_ota.csv
build_flags = 
	${env.build_flags}
	-DHAL=99
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DLOG_BUFFER_SIZE=10240
	-DBOARD_HAS_16MB_FLASH_AND_OTA_SUPPORT
board_upload.maximum_size = 8388608
board_upload.flash_size = 8MB

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
platform = espressif32
board_build.mcu = esp32s3

# Memory & Flash configuration
board_build.flash_mode = qio
board_build.memory_type = qio_opi
board_build.arduino.memory_type = qio_opi
board_build.partitions = custom_16mb_ota.csv
board_upload.maximum_size = 16777216
board_upload.flash_size = 16MB

build_flags = 
    ${env.build_flags}
    -DHAL=99
    -DLOG_BUFFER_SIZE=10240
    -DBOARD_HAS_PSRAM
    -DBOARD_HAS_16MB_FLASH_AND_OTA_SUPPORT
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_ignore = 
    ESP32-A2DP

